version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    volumes:
      - .:/workspace:cached
  frontend:
    build:
      context: .
      dockerfile: dockerfile.web
    ports:
      - "8080:80"
    volumes:
      - .:/workspace:cached
    links:
      - backend
